fixed compilation on Linux
git-svn-id: svn+ssh://svn.code.sf.net/p/fraqtive/code/trunk@113 21e5ddf2-8f81-477f-a659-84387f25dd0c

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -81,7 +81,7 @@ for i in $paths; do
   if test "$version" != "**Unknown**"; then
     major=`echo $version | sed -e "s/\([0-9][0-9]*\).*/\1/"`
     minor=`echo $version | sed -e "s/[0-9][0-9]*\.\([0-9][0-9]*\).*/\1/"`
-    if test $major -eq 4 -a $minor -ge 3; then
+    if test $major -eq 5; then
       QMAKE=$i
       break
     fi
@@ -89,7 +89,7 @@ for i in $paths; do
 done
 
 if test -z "$QMAKE"; then
-    echo "*** ERROR: Cannot find 'qmake' from Qt 4.3 or newer." >&2
+    echo "*** ERROR: Cannot find 'qmake' from Qt 5." >&2
     exit 1
 fi
 
